=== nyradr/HTML_Harvester/HtmlHarvester/dtd/scheme.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT scheme (page*) >
<!ELEMENT page (data*) >
<!ATTLIST page name ID #REQUIRED >

<!ELEMENT data (xpath, xargs*) >
<!ATTLIST data name ID #REQUIRED >
<!ATTLIST data all (0 | 1) "1" #FIXED>
<!ATTLIST data type (txt | att | xml) #REQUIRED >

<!ELEMENT xpath (#PCDATA) >

<!ELEMENT xargs (arg+) >
<!ATTLIST xargs id ID #REQUIRED >

<!ELEMENT arg (#PCDATA) >

=== nyradr/HTML_Harvester/HtmlHarvester/xml/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE scheme SYSTEM "dtd/scheme.dtd" >
<scheme>
	<page name="ql">
		<data name="res" all="0" type="txt">
			<xpath>//div[@class='arg1']/span[@class='arg2']/a</xpath>
			<xargs id="arg1">
				<arg>result</arg>
			</xargs>
			<xargs id="arg2">
				<arg>title</arg>
			</xargs>
		</data>
	</page>
</scheme>
